/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.acilab.stream.processor.wikilinks.serialization;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Token extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4635553825511835662L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Token\",\"namespace\":\"net.acilab.stream.processor.wikilinks.serialization\",\"fields\":[{\"name\":\"tokenstring\",\"type\":\"string\"},{\"name\":\"byteoffset\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Token> ENCODER =
      new BinaryMessageEncoder<Token>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Token> DECODER =
      new BinaryMessageDecoder<Token>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Token> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Token> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Token> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Token>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Token to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Token from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Token instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Token fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence tokenstring;
  @Deprecated public long byteoffset;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Token() {}

  /**
   * All-args constructor.
   * @param tokenstring The new value for tokenstring
   * @param byteoffset The new value for byteoffset
   */
  public Token(java.lang.CharSequence tokenstring, java.lang.Long byteoffset) {
    this.tokenstring = tokenstring;
    this.byteoffset = byteoffset;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tokenstring;
    case 1: return byteoffset;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tokenstring = (java.lang.CharSequence)value$; break;
    case 1: byteoffset = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tokenstring' field.
   * @return The value of the 'tokenstring' field.
   */
  public java.lang.CharSequence getTokenstring() {
    return tokenstring;
  }


  /**
   * Sets the value of the 'tokenstring' field.
   * @param value the value to set.
   */
  public void setTokenstring(java.lang.CharSequence value) {
    this.tokenstring = value;
  }

  /**
   * Gets the value of the 'byteoffset' field.
   * @return The value of the 'byteoffset' field.
   */
  public long getByteoffset() {
    return byteoffset;
  }


  /**
   * Sets the value of the 'byteoffset' field.
   * @param value the value to set.
   */
  public void setByteoffset(long value) {
    this.byteoffset = value;
  }

  /**
   * Creates a new Token RecordBuilder.
   * @return A new Token RecordBuilder
   */
  public static net.acilab.stream.processor.wikilinks.serialization.Token.Builder newBuilder() {
    return new net.acilab.stream.processor.wikilinks.serialization.Token.Builder();
  }

  /**
   * Creates a new Token RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Token RecordBuilder
   */
  public static net.acilab.stream.processor.wikilinks.serialization.Token.Builder newBuilder(net.acilab.stream.processor.wikilinks.serialization.Token.Builder other) {
    if (other == null) {
      return new net.acilab.stream.processor.wikilinks.serialization.Token.Builder();
    } else {
      return new net.acilab.stream.processor.wikilinks.serialization.Token.Builder(other);
    }
  }

  /**
   * Creates a new Token RecordBuilder by copying an existing Token instance.
   * @param other The existing instance to copy.
   * @return A new Token RecordBuilder
   */
  public static net.acilab.stream.processor.wikilinks.serialization.Token.Builder newBuilder(net.acilab.stream.processor.wikilinks.serialization.Token other) {
    if (other == null) {
      return new net.acilab.stream.processor.wikilinks.serialization.Token.Builder();
    } else {
      return new net.acilab.stream.processor.wikilinks.serialization.Token.Builder(other);
    }
  }

  /**
   * RecordBuilder for Token instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Token>
    implements org.apache.avro.data.RecordBuilder<Token> {

    private java.lang.CharSequence tokenstring;
    private long byteoffset;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.acilab.stream.processor.wikilinks.serialization.Token.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tokenstring)) {
        this.tokenstring = data().deepCopy(fields()[0].schema(), other.tokenstring);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.byteoffset)) {
        this.byteoffset = data().deepCopy(fields()[1].schema(), other.byteoffset);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Token instance
     * @param other The existing instance to copy.
     */
    private Builder(net.acilab.stream.processor.wikilinks.serialization.Token other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tokenstring)) {
        this.tokenstring = data().deepCopy(fields()[0].schema(), other.tokenstring);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.byteoffset)) {
        this.byteoffset = data().deepCopy(fields()[1].schema(), other.byteoffset);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'tokenstring' field.
      * @return The value.
      */
    public java.lang.CharSequence getTokenstring() {
      return tokenstring;
    }


    /**
      * Sets the value of the 'tokenstring' field.
      * @param value The value of 'tokenstring'.
      * @return This builder.
      */
    public net.acilab.stream.processor.wikilinks.serialization.Token.Builder setTokenstring(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tokenstring = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tokenstring' field has been set.
      * @return True if the 'tokenstring' field has been set, false otherwise.
      */
    public boolean hasTokenstring() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tokenstring' field.
      * @return This builder.
      */
    public net.acilab.stream.processor.wikilinks.serialization.Token.Builder clearTokenstring() {
      tokenstring = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'byteoffset' field.
      * @return The value.
      */
    public long getByteoffset() {
      return byteoffset;
    }


    /**
      * Sets the value of the 'byteoffset' field.
      * @param value The value of 'byteoffset'.
      * @return This builder.
      */
    public net.acilab.stream.processor.wikilinks.serialization.Token.Builder setByteoffset(long value) {
      validate(fields()[1], value);
      this.byteoffset = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'byteoffset' field has been set.
      * @return True if the 'byteoffset' field has been set, false otherwise.
      */
    public boolean hasByteoffset() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'byteoffset' field.
      * @return This builder.
      */
    public net.acilab.stream.processor.wikilinks.serialization.Token.Builder clearByteoffset() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Token build() {
      try {
        Token record = new Token();
        record.tokenstring = fieldSetFlags()[0] ? this.tokenstring : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.byteoffset = fieldSetFlags()[1] ? this.byteoffset : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Token>
    WRITER$ = (org.apache.avro.io.DatumWriter<Token>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Token>
    READER$ = (org.apache.avro.io.DatumReader<Token>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tokenstring);

    out.writeLong(this.byteoffset);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tokenstring = in.readString(this.tokenstring instanceof Utf8 ? (Utf8)this.tokenstring : null);

      this.byteoffset = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tokenstring = in.readString(this.tokenstring instanceof Utf8 ? (Utf8)this.tokenstring : null);
          break;

        case 1:
          this.byteoffset = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










